### PR TITLE
GH-364 add openssl devel package (if version >=1.1.1 exists)

### PR DESCRIPTION
**Pull request by adrianopol**
roc-streaming/roc-toolkit#364

@gavv , not sure if I should add it to the toolchain-* Dockerfiles

### CODE REVIEW

**Comment by gavv** [comment]
No need to add it to toolchains, those images are for crosscompilation, native libs are not needed.

For the same reason, it shouldn't be added to env-android.

Also please remove it from env-ubuntu-minimal, this image is for testing environment without preinstalled libs.

**Comment by adrianopol** [comment]
> Also please remove it from env-ubuntu-minimal, this image is for testing environment without preinstalled libs.

Are you sure about ubuntu-minimal? It already has libpulse-dev and libasound2-dev.

**Comment by gavv** [comment]
TBH I don't remember why it has them, but it doesn't have other libs.

Maybe because we can't really work with alsa and pulse different from installed on system.

We should check this, maybe we can remove them actually.

**Comment by adrianopol** [comment]
> No need to add it to toolchains, those images are for crosscompilation, native libs are not needed.
> 
> For the same reason, it shouldn't be added to env-android.
> 
> Also please remove it from env-ubuntu-minimal, this image is for testing environment without preinstalled libs.

done

**Pull request merged**
