### PR TITLE
Add travis-ubuntu:20.04

### PR DESCRIPTION
**Pull request by Villaquiranm**
Add travis-ubuntu:20.04

### CODE REVIEW

**Comment by gavv** [comment]
Thanks! LGTM.

I've rebased it on fresh master and also added a few more compilers. Let's explicitly cover them in the travis script. We'll also have to update [this page](https://roc-project.github.io/roc/docs/development/continuous_integration.html) and add the new compiler versions to the "Linux native" table.

Also, I suspect that after adding ubuntu 20 and all these compilers, "Linux x86_64" travis job can become too long. If it will take more than 35 mins, we can try to extract ubuntu part to a separate job "Linux Ubuntu x86_64". This way ubuntu and non-ubuntu jobs will run in parallel.

**Comment by gavv** [comment]
I've added 20.04 tag to docker hub. The new tag will appear in a few hours, I think: https://hub.docker.com/r/rocproject/travis-ubuntu/tags

**Comment by Villaquiranm** [comment]
Hello @gavv I've waiting and the tag is not there, when i try to pull the image i got:

`docker pull rocproject/travis-ubuntu:20.04`
`Error response from daemon: manifest for rocproject/travis-ubuntu:20.04 not found: manifest unknown: manifest unknown
`

Do you think something was not done properly ?

**Comment by gavv** [comment]
Hm, the tag build was not triggered for some reason. I triggered it manually and the tag is now available.

**Pull request merged**
